apiVersion: v1
kind: Secret
metadata:
  name: app-of-apps-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/danielyaba/argocd-app-of-apps.git